# Generated by Django 4.1.5 on 2023-01-31 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_orm', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
