# Generated by Django 4.1.5 on 2023-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orm', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTableV2',
            fields=[
                ('int_field', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('char_field', models.CharField(max_length=200)),
                ('date_field', models.DateField()),
                ('date_time_field', models.DateTimeField()),
            ],
        ),
    ]
