# Generated by Django 4.1.5 on 2023-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_orm', '0004_testtablev2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtablev2',
            name='int_field',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
